# Generated by Django 5.2.6 on 2025-09-22 13:05

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_rename_bio_user_user_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_nickname',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='昵称'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
